// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartRecord() {
  return window['go']['main']['App']['StartRecord']();
}

export function StopRecord() {
  return window['go']['main']['App']['StopRecord']();
}
